version: '3.9'

services:
  natal-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: natal-api
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: unless-stopped